var TestMapData = {
	groundBlocks: [
		{ indexXZ: { x: 0,   z: 0 },   groundtype: "grass" },
		{ indexXZ: { x: 1,   z: 0 },   groundtype: "grass" },
		{ indexXZ: { x: 2,   z: 0 },   groundtype: "grass" },
		{ indexXZ: { x: 3,   z: 0 },   groundtype: "grass" },
		{ indexXZ: { x: 4,   z: 0 },   groundtype: "grass" },
		{ indexXZ: { x: 5,   z: 0 },   groundtype: "grass" },
		{ indexXZ: { x: 6,   z: 0 },   groundtype: "grass" },
		{ indexXZ: { x: 7,   z: 0 },   groundtype: "grass" },
		{ indexXZ: { x: 8,   z: 0 },   groundtype: "grass" },
		{ indexXZ: { x: 9,   z: 0 },   groundtype: "grass" },
		
		{ indexXZ: { x: 0,   z: 1 },   groundtype: "grass" },
		{ indexXZ: { x: 1,   z: 1 },   groundtype: "dirt" },
		{ indexXZ: { x: 2,   z: 1 },   groundtype: "grass" },
		{ indexXZ: { x: 3,   z: 1 },   groundtype: "grass" },
		{ indexXZ: { x: 4,   z: 1 },   groundtype: "grass" },
		{ indexXZ: { x: 5,   z: 1 },   groundtype: "grass" },
		{ indexXZ: { x: 6,   z: 1 },   groundtype: "grass" },
		{ indexXZ: { x: 7,   z: 1 },   groundtype: "grass" },
		{ indexXZ: { x: 8,   z: 1 },   groundtype: "grass" },
		{ indexXZ: { x: 9,   z: 1 },   groundtype: "grass" },
		
		{ indexXZ: { x: 0,   z: 2 },   groundtype: "grass" },
		{ indexXZ: { x: 1,   z: 2 },   groundtype: "dirt" },
		{ indexXZ: { x: 2,   z: 2 },   groundtype: "grass" },
		{ indexXZ: { x: 3,   z: 2 },   groundtype: "grass" },
		{ indexXZ: { x: 4,   z: 2 },   groundtype: "grass" },
		{ indexXZ: { x: 5,   z: 2 },   groundtype: "grass" },
		{ indexXZ: { x: 6,   z: 2 },   groundtype: "grass" },
		{ indexXZ: { x: 7,   z: 2 },   groundtype: "grass" },
		{ indexXZ: { x: 8,   z: 2 },   groundtype: "grass" },
		{ indexXZ: { x: 9,   z: 2 },   groundtype: "grass" },
		
		{ indexXZ: { x: 0,   z: 3 },   groundtype: "grass" },
		{ indexXZ: { x: 1,   z: 3 },   groundtype: "dirt" },
		{ indexXZ: { x: 2,   z: 3 },   groundtype: "grass" },
		{ indexXZ: { x: 3,   z: 3 },   groundtype: "grass" },
		{ indexXZ: { x: 4,   z: 3 },   groundtype: "grass" },
		{ indexXZ: { x: 5,   z: 3 },   groundtype: "grass" },
		{ indexXZ: { x: 6,   z: 3 },   groundtype: "grass" },
		{ indexXZ: { x: 7,   z: 3 },   groundtype: "grass" },
		{ indexXZ: { x: 8,   z: 3 },   groundtype: "grass" },
		{ indexXZ: { x: 9,   z: 3 },   groundtype: "grass" },
		
		{ indexXZ: { x: 0,   z: 4 },   groundtype: "grass" },
		{ indexXZ: { x: 1,   z: 4 },   groundtype: "dirt" },
		{ indexXZ: { x: 2,   z: 4 },   groundtype: "grass" },
		{ indexXZ: { x: 3,   z: 4 },   groundtype: "grass" },
		{ indexXZ: { x: 4,   z: 4 },   groundtype: "grass" },
		{ indexXZ: { x: 5,   z: 4 },   groundtype: "grass" },
		{ indexXZ: { x: 6,   z: 4 },   groundtype: "grass" },
		{ indexXZ: { x: 7,   z: 4 },   groundtype: "grass" },
		{ indexXZ: { x: 8,   z: 4 },   groundtype: "grass" },
		{ indexXZ: { x: 9,   z: 4 },   groundtype: "grass" },
		
		{ indexXZ: { x: 0,   z: 5 },   groundtype: "grass" },
		{ indexXZ: { x: 1,   z: 5 },   groundtype: "grass" },
		{ indexXZ: { x: 2,   z: 5 },   groundtype: "grass" },
		{ indexXZ: { x: 3,   z: 5 },   groundtype: "grass" },
		{ indexXZ: { x: 4,   z: 5 },   groundtype: "grass" },
		{ indexXZ: { x: 5,   z: 5 },   groundtype: "grass" },
		{ indexXZ: { x: 6,   z: 5 },   groundtype: "grass" },
		{ indexXZ: { x: 7,   z: 5 },   groundtype: "grass" },
		{ indexXZ: { x: 8,   z: 5 },   groundtype: "grass" },
		{ indexXZ: { x: 9,   z: 5 },   groundtype: "grass" },
		
		{ indexXZ: { x: 0,   z: 6 },   groundtype: "grass" },
		{ indexXZ: { x: 1,   z: 6 },   groundtype: "water" },
		{ indexXZ: { x: 2,   z: 6 },   groundtype: "grass" },
		{ indexXZ: { x: 3,   z: 6 },   groundtype: "grass" },
		{ indexXZ: { x: 4,   z: 6 },   groundtype: "grass" },
		{ indexXZ: { x: 5,   z: 6 },   groundtype: "grass" },
		{ indexXZ: { x: 6,   z: 6 },   groundtype: "grass" },
		{ indexXZ: { x: 7,   z: 6 },   groundtype: "grass" },
		{ indexXZ: { x: 8,   z: 6 },   groundtype: "grass" },
		{ indexXZ: { x: 9,   z: 6 },   groundtype: "grass" },
		
		{ indexXZ: { x: 0,   z: 7 },   groundtype: "grass" },
		{ indexXZ: { x: 1,   z: 7 },   groundtype: "water" },
		{ indexXZ: { x: 2,   z: 7 },   groundtype: "grass" },
		{ indexXZ: { x: 3,   z: 7 },   groundtype: "grass" },
		{ indexXZ: { x: 4,   z: 7 },   groundtype: "grass" },
		{ indexXZ: { x: 5,   z: 7 },   groundtype: "grass" },
		{ indexXZ: { x: 6,   z: 7 },   groundtype: "grass" },
		{ indexXZ: { x: 7,   z: 7 },   groundtype: "grass" },
		{ indexXZ: { x: 8,   z: 7 },   groundtype: "grass" },
		{ indexXZ: { x: 9,   z: 7 },   groundtype: "grass" },
		
		{ indexXZ: { x: 0,   z: 8 },   groundtype: "grass" },
		{ indexXZ: { x: 1,   z: 8 },   groundtype: "water" },
		{ indexXZ: { x: 2,   z: 8 },   groundtype: "grass" },
		{ indexXZ: { x: 3,   z: 8 },   groundtype: "grass" },
		{ indexXZ: { x: 4,   z: 8 },   groundtype: "grass" },
		{ indexXZ: { x: 5,   z: 8 },   groundtype: "grass" },
		{ indexXZ: { x: 6,   z: 8 },   groundtype: "grass" },
		{ indexXZ: { x: 7,   z: 8 },   groundtype: "grass" },
		{ indexXZ: { x: 8,   z: 8 },   groundtype: "grass" },
		{ indexXZ: { x: 9,   z: 8 },   groundtype: "grass" },
		
		{ indexXZ: { x: 0,   z: 9 },   groundtype: "grass" },
		{ indexXZ: { x: 1,   z: 9 },   groundtype: "grass" },
		{ indexXZ: { x: 2,   z: 9 },   groundtype: "grass" },
		{ indexXZ: { x: 3,   z: 9 },   groundtype: "grass" },
		{ indexXZ: { x: 4,   z: 9 },   groundtype: "grass" },
		{ indexXZ: { x: 5,   z: 9 },   groundtype: "grass" },
		{ indexXZ: { x: 6,   z: 9 },   groundtype: "grass" },
		{ indexXZ: { x: 7,   z: 9 },   groundtype: "grass" },
		{ indexXZ: { x: 8,   z: 9 },   groundtype: "grass" },
		{ indexXZ: { x: 9,   z: 9 },   groundtype: "grass" },
	],
	objects: [
		{ indexXZ: { x: 7,   z: 4 },     objecttype: "tree" },
		{ indexXZ: { x: 7,   z: 6 },     objecttype: "bed",		direction: "south" },
	],
	characters: [
		{ indexXZ: { x: 5,   z: 5 } },
	],
};